swagger: '2.0'
info:
  version: "1.0.0"
  title: User API
tags:
  - name: User
    description: Operations about users
paths:
  /users:
    get:
      tags:
        - User
      summary: Get all users
      operationId: getUsers
      responses:
        '200':
          description: A list of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      tags:
        - User
      summary: Create a user
      operationId: createUser
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/CreateUserRequest'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'
  /users/{id}:
    get:
      tags:
        - User
      summary: Get a user by ID
      operationId: getUserById
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: A single user
          schema:
            $ref: '#/definitions/User'
    put:
      tags:
        - User
      summary: Update a user by ID
      operationId: updateUserById
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UpdateUserRequest'
      responses:
        '200':
          description: Updated
          schema:
            $ref: '#/definitions/User'
    delete:
      tags:
        - User
      summary: Delete a user by ID
      operationId: deleteUserById
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '204':
          description: No Content
definitions:
  User:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      email:
        type: string
  CreateUserRequest:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
  UpdateUserRequest:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
  Error:
    type: object
    properties:
      message:
        type: string
      code:
        type: integer
